<!DOCTYPE html>
<html lang="en">

    @section('title')

    {{__('Privacy Policy') }}
    @endsection
        @include('layouts.front_header')
        <!-- [ Header ] start -->
        <header id="home" class="bg-primary blog_detail">
          <div class="container">
            <div class="row align-items-center justify-content-center text-center">
              <div class="col-sm-12">
                <h1
                  class="text-white mb-sm-4 wow animate__fadeInLeft"
                  data-wow-delay="0.2s"
                >
                {{__('Privacy Policy')}}
                </h1>
              </div>
            </div>
          </div>
        </header>
        <!-- [ Header ] End -->

    <section>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <article class="article article-detail article-noshadow">
                        <div class="p-0">
                            <!--<div>-->
                            <!--    {!! Utility::getsettings('privacy') !!}-->
                            <!--</div>-->
                            
<p><span style="font-size: 18pt;"><strong>Privacy Policy for Stop Cannabis Challenge</strong></span></p>
<p><br><span style="font-size: 18pt;"><strong>Privacy Policy</strong></span></p>
<p><br>Last updated: August 18, 2023<br>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service<br>and tells You about Your privacy rights and how the law protects You.<br>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in<br>accordance with this Privacy Policy.</p>
<p><br><strong><span style="font-size: 18pt;">Interpretation and Definitions</span></strong></p>
<p><strong><span style="font-size: 18pt;">Interpretation</span></strong></p>
<p><br>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the<br>same meaning regardless of whether they appear in singular or in plural.</p>
<p><br><strong><span style="font-size: 18pt;">Definitions</span></strong></p>
<p><br>For the purposes of this Privacy Policy:</p>
<ul>
<li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
<li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50%<br>or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
<li><strong>Application</strong> refers to Stop Cannabis Challenge, the software program provided by the Company.</li>
<li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Sarrasa Consulting Inc., 301 Pimlico Dr.<br>Oshawa ON L1L 0L3.</li>
<li><strong>Country</strong> refers to: Ontario, Canada</li>
<li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
<li><strong>Personal</strong> <strong>Data</strong> is any information that relates to an identified or identifiable individual</li>
<li><strong>Service</strong> refers to the Application.</li>
<li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies<br>or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services<br>related to the Service or to assist the Company in analyzing how the Service is used.</li>
<li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for<br>example, the duration of a page visit).</li>
<li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is<br>accessing or using the Service, as applicable.</li>
</ul>
<p><strong><span style="font-size: 18pt;">Collecting and Using Your Personal Data</span></strong></p>
<p><strong><span style="font-size: 14pt;">Types of Data Collected</span></strong></p>
<p><span style="font-size: 14pt;"><strong>Personal Data</strong></span></p>
<p><span style="font-size: 10pt;">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify<br>You. Personally identifiable information may include, but is not limited to:</span></p>
<ul>
<li><span style="font-size: 10pt;">Email address</span></li>
<li><span style="font-size: 10pt;">First name and last name</span></li>
<li><span style="font-size: 10pt;">Phone number</span></li>
<li><span style="font-size: 10pt;">Address, State, Province, ZIP/Postal code, City</span></li>
<li><span style="font-size: 10pt;">Usage Data<br></span></li>
</ul>
<p><strong><span style="font-size: 18pt;">Usage Data</span></strong></p>
<p><span style="font-size: 12pt;">Usage Data is collected automatically when using the Service.</span></p>
<p><span style="font-size: 12pt;">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the<br>pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other<br>diagnostic data.</span></p>
<p><span style="font-size: 12pt;">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the<br>type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of<br>mobile Internet browser You use, unique device identifiers and other diagnostic data.</span></p>
<p><span style="font-size: 12pt;">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a<br>mobile device.</span></p>
<p><strong><span style="font-size: 18pt;">Use of Your Personal Data</span></strong></p>
<p><span style="font-size: 12pt;">The Company may use Personal Data for the following purposes:</span></p>
<ul>
<li><span style="font-size: 12pt;">To provide and maintain our Service, including to monitor the usage of our Service</span></li>
<li><span style="font-size: 12pt;">To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to<br>different functionalities of the Service that are available to You as a registered user</span></li>
<li><span style="font-size: 12pt;">For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or<br>services You have purchased or of any other contract with Us through the Service.</span></li>
<li><span style="font-size: 12pt;">To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile<br>application's push notifications regarding updates or informative communications related to the functionalities, products or contracted<br>services, including the security updates, when necessary or reasonable for their implementation.</span></li>
<li><span style="font-size: 12pt;">To provide You with news, special offers and general information about other goods, services and events which we offer that are similar<br>to those that you have already purchased or enquired about unless You have opted not to receive such information.</span></li>
<li><span style="font-size: 12pt;">To manage Your requests: To attend and manage Your requests to Us</span></li>
<li><span style="font-size: 12pt;">For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization,<br>dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or<br>similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</span></li>
<li><span style="font-size: 12pt;">For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the<br>effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</span></li>
</ul>
<p><span style="font-size: 12pt;">We may share Your personal information in the following situations:</span></p>
<ul>
<li><span style="font-size: 12pt;">With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service,<br>to contact You.</span></li>
<li><span style="font-size: 12pt;">For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger,<br>sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</span></li>
<li><span style="font-size: 12pt;">With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy<br>Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that<br>are under common control with Us.</span></li>
<li><span style="font-size: 12pt;">With business partners: We may share Your information with Our business partners to offer You certain products, services or<br>promotions.</span></li>
<li><span style="font-size: 12pt;">With other users: when You share personal information or otherwise interact in the public areas with other users, such information may<br>be viewed by all users and may be publicly distributed outside.</span></li>
<li><span style="font-size: 12pt;">With Your consent: We may disclose Your personal information for any other purpose with Your consent.</span></li>
</ul>
<p><strong><span style="font-size: 18pt;">Retention of Your Personal Data</span></strong></p>
<p><span style="font-size: 12pt;">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and<br>use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to<br>comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</span></p>
<p><span style="font-size: 12pt;">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except<br>when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for<br>longer time periods.</span></p>
<p><strong><span style="font-size: 18pt;">Transfer of Your Personal Data</span></strong></p>
<p><span style="font-size: 12pt;">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved<br>in the processing are located. It means that this information may be transferred to &mdash; and maintained on &mdash; computers located outside of Your<br>state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</span></p>
<p><span style="font-size: 12pt;"><br>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.<br>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy<br>and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the<br>security of Your data and other personal information</span></p>
<p><strong><span style="font-size: 18pt;">Delete Your Personal Data</span></strong></p>
<p><span style="font-size: 12pt;">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.<br>Our Service may give You the ability to delete certain information about You from within the Service.<br>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings<br>section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal<br>information that You have provided to Us.<br>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</span></p>
<p><span style="font-size: 18pt;"><strong>Disclosure of Your Personal Data</strong></span></p>
<p><span style="font-size: 14pt;"><strong>Business Transactions</strong></span></p>
<p><span style="font-size: 12pt;">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your<br>Personal Data is transferred and becomes subject to a different Privacy Policy</span></p>
<p><span style="font-size: 14pt;"><strong>Law enforcement</strong></span></p>
<p><span style="font-size: 12pt;">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid<br>requests by public authorities (e.g. a court or a government agency).</span></p>
<p><span style="font-size: 14pt;"><strong>Other legal requirements</strong></span></p>
<p><span style="font-size: 12pt;">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</span></p>
<ul>
<li><span style="font-size: 12pt;">Comply with a legal obligation</span></li>
<li><span style="font-size: 12pt;">Protect and defend the rights or property of the Company</span></li>
<li><span style="font-size: 12pt;">Prevent or investigate possible wrongdoing in connection with the Service</span></li>
<li><span style="font-size: 12pt;">Protect the personal safety of Users of the Service or the public</span></li>
<li><span style="font-size: 12pt;">Protect against legal liability</span></li>
</ul>
<p><span style="font-size: 14pt;"><strong>Security of Your Personal Data</strong></span></p>
<p><span style="font-size: 12pt;">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic<br>storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its<br>absolute security.</span></p>
<p><span style="font-size: 18pt;"><strong>Children's Privacy</strong></span></p>
<p><span style="font-size: 12pt;">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under<br>the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We<br>become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps<br>to remove that information from Our servers.</span></p>
<p><span style="font-size: 12pt;">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require<br>Your parent's consent before We collect and use that information</span></p>
<p><span style="font-size: 18pt;"><strong>Links to Other Websites</strong></span></p>
<p><span style="font-size: 12pt;">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third<br>party's site. We strongly advise You to review the Privacy Policy of every site You visit.<br>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</span></p>
<p><span style="font-size: 18pt;"><strong>Changes to this Privacy Policy</strong></span></p>
<p><span style="font-size: 12pt;">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.<br>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated"<br>date at the top of this Privacy Policy.<br>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on<br>this page.</span></p>
<p><span style="font-size: 18pt;"><strong>Contact Us</strong></span></p>
<p><span style="font-size: 12pt;">If you have any questions about this Privacy Policy, You can contact us;</span></p>
<ul>
<li><span style="font-size: 12pt;">By email: michael.chaiton@camh.ca</span></li>
</ul>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
                        </div>
                    </article>
                </div>
            </div>
        </div>
    </section>

     <!--@include('layouts.front_footer') -->

</body>

</html>
